# -*- coding: utf-8 -*-
"""Prak7_LatihanKedua.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1avlWgwKB3g-PJyNNxWst59sVOzU5rhqb
"""

from google.colab import files
import pandas as pd
#memanggil dan menampilkan dataset
uploaded =  files.upload()
data_novandy = pd.read_csv('titanic.csv')
print(data_novandy)

#mengambil data pada kolom tertentu
data_a = data_novandy.loc[:,['Sex']]
print(data_a)

#memanipulasi data jumlah penumpang berdasarkan kolom sex
data_b = data_novandy[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
penumpang = data_b.groupby('Sex')['Name'].nunique()
print('Jumlah Penumpang:\n', penumpang)

#memfilter data penumpang yang selamat berdasarkan kolom sex
data_c = data_novandy[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
takselamat = data_c['Sex'].loc[data_novandy['Survived']==0]
print('Penumpang yang tidak selamat:\n', takselamat.value_counts())
selamat = data_c['Pclass'].loc[data_novandy['Survived']==1]
print('\nPenumpang yang selamat:\n', selamat.value_counts())